---
# Setup fixtures (themes, wallpapers, etc.)
setup_fixtures: true

configure_explorer: true
configure_hostname: false
custom_hostname: windows-ansible
configure_start_menu: true
configure_taskbar: true
disable_mouse_acceleration: true
remote_desktop_enabled: false
remove_desktop_icons: false
set_sound_scheme: true

install_windows_updates: true
windows_updates_reboot: true
update_categories:
  # You can install only specific updates by uncommenting it
  # * - installs all updates
  # - "*"
  - Critical Updates
  # - Definition Updates
  # - Developer Kits
  # - Feature Packs
  - Security Updates
  # - Service Packs
  # - Tools
  - Update Rollups
  # - Updates
  # - Upgrades

change_power_plan: true
# high_performance
# balanced
# power_saver
power_plan: "balanced"

install_chocolatey_packages: true
choco_installed_packages:

install_winget_packages: true
winget_packages:
  # dev tools
  - name: Microsoft.WindowsTerminal
    source: winget
  - name: JanDeDobbeleer.OhMyPosh
    source: winget
  - name: chrisant996.Clink
    source: winget
  - name: junegunn.fzf
    source: winget
  - name: ajeetdsouza.zoxide
    source: winget
  - name: JesseDuffield.Lazydocker
    source: winget
  - name: lazygit.lazygit
    source: winget
  - name: Git.Git
    source: winget
    arguments: >
      --custom '/components="gitlfs,assoc,autoupdate,windowsterminal /TASKS=!desktopicon,gitbashprofile /DEFAULTBRANCH=main /USEGITOPTIONALTOOLS=true"'

  - name: Microsoft.VisualStudioCode
    source: winget
  - name: Docker.DockerDesktop
    source: winget
  - name: Anaconda.Miniconda3
    source: winget

  # fun tools 
  - name: Microsoft.PowerToys
    source: winget
  - name: Flow-Launcher.Flow-Launcher
    source: winget

  # gui stuffs
  - name: Mozilla.Firefox
    source: winget
  - name: 7zip.7zip
    source: winget

# Terminal customization
install_fonts: true
installed_nerdfonts:
  - cascadiacode

install_ohmyposh: true

# List of features: "Get-WindowsOptionalFeature -Online"
install_windows_features: false
windows_features:
  Microsoft-Hyper-V: true

install_wsl2: true
wsl2_distribution: 
  wsl-ubuntu-2004

remove_bloatware: true
bloatware:
  - Microsoft.BingNews
  - Microsoft.BingWeather
  - Microsoft.GamingApp
  - Microsoft.GetHelp
  - Microsoft.Getstarted
  - Microsoft.Messaging
  - Microsoft.Microsoft3DViewer
  - Microsoft.MicrosoftOfficeHub
  - Microsoft.MicrosoftSolitaireCollection
  - Microsoft.MicrosoftStickyNotes
  - Microsoft.MixedReality.Portal
  # - Microsoft.MSPaint
  - Microsoft.Office.OneNote
  - Microsoft.OneConnect
  - Microsoft.People
  - Microsoft.PowerAutomateDesktop
  - Microsoft.Print3D
  - Microsoft.ScreenSketch
  - Microsoft.SkypeApp
  - Microsoft.Todos
  - Microsoft.Windows.Photos
  - Microsoft.WindowsAlarms
  # - Microsoft.WindowsCalculator
  - Microsoft.Wallet
  - Microsoft.WindowsCamera
  - microsoft.windowscommunicationsapps
  - Microsoft.WindowsFeedbackHub
  - Microsoft.WindowsMaps
  - Microsoft.WindowsSoundRecorder
  - Microsoft.Xbox
  - Microsoft.Xbox.TCUI
  - Microsoft.XboxApp
  - Microsoft.XboxGameOverlay
  - Microsoft.XboxSpeechToTextOverlay
  - Microsoft.YourPhone
  - Microsoft.ZuneMusic
  - Microsoft.ZuneVideo
  - MicrosoftTeams

configure_storage_sense: false
storage_sense:
  enabled: true
  run_frequency: 1
  delete_unused_files: true
  delete_recycle_bin_files: true
  recycle_bin_age: 14
  delete_downloads_files: true
  downloads_age: 14

defrag_volumes: false
include_volumes:
  - C





### deprecated stuffs

# install_chocolatey_packages: true
# choco_installed_packages:
