---
- name: Install nerdfonts
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    choco_args: "{{ item.choco_args | default(omit) }}"
  loop: "{{ installed_nerdfonts }}"